### ISSUE TITLE
Debian compatibility 

### ISSUE THREAD

**Issue by mYnDstrEAm** [Intika-Linux-Apps/Startup-Watcher#2] opened 2019-06-11 14:16 UTC
When starting it I get a lot of file or directory not found messages. For example for:

/home/username/.startup-watcher/up* and /home/username/.kde/Autostart/

I also get /bin/cat: /var/spool/cron/crontabs: no permission

When I click on the tray icon to open the application I get:

> Failed to execute "/bin/bash", error code: 127.
> 
> Press OK to ignore and risk data corruption.
> Press Cancel to kill the program.

and these messages:

> /bin/bash: /bin/diff: File or directory not found

I'm running Debian with KDE and have diffutils installed. bin/diff doesn't exist. Do I need to install some other package, create a link or add some path variables?

Also could you get this onto the Debian repositories later?

Thank you for this app!

**Comment by intika** [comment] 2019-06-12 19:02
Can you please check if those files exist (i will update the app to fix the compatibility)
/usr/bin/diff
/ur/bin/bash
/usr/bin/sh
/bin/bash
/bin/sh
/bin/cat
/usr/bin/cat

This application can be added to most distros repository but right now it's a little young, also as it's written in delphi/pascal there is no true needs for dependency or else, the binary is enough to make it run everywhere... but yes i will probably add deb and rpm packages later on.
 
for this `I also get /bin/cat: /var/spool/cron/crontabs: no permission` we will check that error after fixing the main one... ;)

**Comment by mYnDstrEAm** [comment] 2019-06-12 20:26
These don't exist:
/usr/bin/bash
/usr/bin/sh
/usr/bin/cat

>  but yes i will probably add deb and rpm packages later on

Sounds great!

**Comment by intika** [comment] 2019-06-12 22:15
/usr/bin/diff -------- 
/ur/bin/bash ------- x
/usr/bin/sh --------- x
/bin/bash ----------
/bin/sh -------------
/bin/cat ------------
/bin/diff ------------ x
/usr/bin/cat ------- x

> /home/username/.startup-watcher/up* and /home/username/.kde/Autostart/

> I also get /bin/cat: /var/spool/cron/crontabs: no permission

**Comment by mYnDstrEAm** [comment] 2019-06-12 22:33
Those other files do exist in these locations.  
Below are all the error messages I get before I click the tray icon. I was trying to get all error messages in English but some of them stay German even though `locale` shows `en_US.UTF-8` for all settings - just like I configured it again before signing back in. Couldn't change that so far.

> /bin/cp: der Aufruf von stat für '/home/username/.startup-watcher/up*' ist nicht möglich: Datei oder Verzeichnis nicht gefunden
> /bin/cp: der Aufruf von stat für '/home/username/.startup-watcher/prev*' ist nicht möglich: Datei oder Verzeichnis nicht gefunden
> /bin/cp: der Aufruf von stat für '/home/username/.startup-watcher/dif*' ist nicht möglich: Datei oder Verzeichnis nicht gefunden
> Startup-watcher: found previous scan on /home/username/.startup-watcher/*, loading datas
> /bin/ls: Zugriff auf '/etc/xdg/openbox/' nicht möglich: Datei oder Verzeichnis nicht gefunden
> /bin/cat: /var/spool/cron/crontabs: Keine Berechtigung
> /bin/cat: '/etc/xdg/openbox/*': Datei oder Verzeichnis nicht gefunden
> /bin/cat: /bin/cat: /etc/lxdm/Xsession/bin/bash: /bin/crontab: Datei oder Verzeichnis nicht gefunden
> : Datei oder Verzeichnis nicht gefunden
> /etc/gdm/Xsession: Datei oder Verzeichnis nicht gefunden
> /bin/ls: Zugriff auf '/home/username/.config/openbox/' nicht möglich: Datei oder Verzeichnis nicht gefunden
> /bin/cat: /etc/rc.local/bin/cat: cat: /etc/rc.d/rc.local: Datei oder Verzeichnis nicht gefunden/etc/lightdm/Xsession: Datei oder Verzeichnis nicht gefunden: Datei oder Verzeichnis nicht gefunden
> 
> 
> /bin/cat: /home/username/.xprofile: Datei oder Verzeichnis nicht gefunden
> /bin/cat: /home/username/.xsession: Datei oder Verzeichnis nicht gefunden                                         
> /bin/cat: /bin/ls: '/home/username/.config/openbox/*': Datei oder Verzeichnis nicht gefunden                      
> Zugriff auf '/home/username/.kde/Autostart/' nicht möglich: Datei oder Verzeichnis nicht gefunden 

Datei oder Verzeichnis nicht gefunden = File or directory not found.

`home/username/.startup-watcher/` does exist and contains files such as "up0". `/home/username/.kde/` doesn't contain a folder called "autostart".

**Comment by intika** [comment] 2019-06-12 22:38
Don't worry... 

I just updated the application to v1.4 it should be fixed can you try with the latest version... 

For `/home/username/.kde/` just ignore the error message; as well for `/bin/cat: /var/spool/cron/crontabs: no permission` just ignore it, as the application also check crons with `crontab -l` so it does not matter if it is not having access to `cron/crontabs`

The other errors you are getting are caused by the main one, that i just fixed...

**Comment by intika** [comment] 2019-06-12 22:43
Closing this... let me know if it worked... rpm/deb package task is added to  https://github.com/Intika-Linux-Apps/Startup-Watcher/issues/1

**Closed as completed by intika** 2019-06-12 22:43 UTC

**Comment by intika** [comment] 2019-06-12 22:47
Also note that the application check for more than 32 locations. different systems may miss one or many locations; this would result in message like `/bin/cat: /home/username/.xprofile: No such file or directory` just ignore those messages (as your system is not using those locations)

**Comment by intika** [comment] 2019-06-12 23:06
Also you may check https://github.com/Intika-Linux-Apps/Startup-Watcher/issues/3 ... let me know if everything is okay ;)

**Comment by mYnDstrEAm** [comment] 2019-06-13 09:11
It's working now - thank you.

For the error message I'd think that one first needs to check if the directories or files exist to prevent the error messages.

Now it would be cool if it could not only show me the changes since last visit but also from a specified date (for all startup-files).  
Maybe there could be some integration with [etckeeper](https://etckeeper.branchable.com/).  
And of course the thing that would make this tool a lot more useful would be to have it interpret the data to process the textfiles so that it shows a clean list with startup entries...and to allow the user to de/activate an entry with a simple click of a button and entering the password. For processing the textcontents this list could be useful: http://wiki.ubuntu.com/InitScriptHumanDescriptions

These are something in between questions and new issues. If that's fine I'll make new issues for them.

**Comment by intika** [comment] 2019-06-13 12:26
It's fine here i'll add things to the https://github.com/Intika-Linux-Apps/Startup-Watcher/issues/1 to make it manageable simply... 

i still need to fix the backup system that generate this error `/bin/cp: der Aufruf von stat für '/home/username/.startup-watcher/up*' ist nicht möglich: Datei oder Verzeichnis nicht gefunden` i'll update that soon, it's not working properly right now. 

Yeah the idea at first was to make a list with checkbox to disable/enable the listed items but i had a limited time to create the application so i just went with the text solution (take less time to develop) i'll may be update the application with advanced option if i have the time for it. 

for the changes overtime the application already save a log of the different changes overtime to `~/.startup-watcher/changes` it does not show the information directly on the main application but those log files can be read with a text editor, the file are names like this [Row.number]-[Prev/Diff/New]-[Date] where prev stand for previous state, Diff for the captured changes and New for the new state. 

I'll checkout the tools you linked to see if i can do something, but as i already said the time i have for this app is limited.

**Comment by intika** [comment] 2019-06-13 20:59
- Just fixed the backup feature/error 
- Added support for multiple change at once
- The errors are now displayed/saved to the gui (text file)
